<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Kdecom\Module'                                    => __DIR__ . '/Module.php',
    'Kdecom\Form\ProvidesEventsForm'                   => __DIR__ . '/src/Kdecom/Form/ProvidesEventsForm.php',
    'Kdecom\Mapper\Exception\ExceptionInterface'       => __DIR__ . '/src/Kdecom/Mapper/Exception/ExceptionInterface.php',
    'Kdecom\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/Kdecom/Mapper/Exception/InvalidArgumentException.php',
    'Kdecom\Mapper\AbstractDbMapper'                   => __DIR__ . '/src/Kdecom/Mapper/AbstractDbMapper.php',
    'Kdecom\EventManager\EventProvider'                => __DIR__ . '/src/Kdecom/EventManager/EventProvider.php',
    'Kdecom\Module\AbstractModule'                     => __DIR__ . '/src/Kdecom/Module/AbstractModule.php',
    'Kdecom\Mvc\Controller\ActionController'           => __DIR__ . '/src/Kdecom/Mvc/Controller/ActionController.php',
    'Kdecom\Mvc\Controller\AdminActionController'      => __DIR__ . '/src/Kdecom/Mvc/Controller/AdminActionController.php',
);